### ISSUE TITLE
Number format Error connecting to Couchbase server in Docker

### ISSUE THREAD

**Issue by Tusshu** [couchbase/docker#128]
Installed Couchbase docker image using instruction provided at the link below.
[https://docs.couchbase.com/server/current/install/getting-started-docker.html]

Docker is running on Mac OS Mojave version 10.14.5. Java SDK version 2.7. Please help!

Trying to connect using Java SDK client as follows:
`cluster = CouchbaseCluster.create("http://localhost:8091/pools");` 

Following error is reported:
java.lang.NumberFormatException: For input string: "8091/pools"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.base/java.lang.Integer.parseInt(Integer.java:652)
        at java.base/java.lang.Integer.parseInt(Integer.java:770)
        at com.couchbase.client.core.utils.ConnectionString.parseHosts(ConnectionString.java:127)
        at com.couchbase.client.core.utils.ConnectionString.<init>(ConnectionString.java:52)
        at com.couchbase.client.core.utils.ConnectionString.create(ConnectionString.java:58)
        at com.couchbase.client.core.utils.ConnectionString.fromHostnames(ConnectionString.java:69)
        at com.couchbase.client.java.CouchbaseCluster.create(CouchbaseCluster.java:171)
        at com.couchbase.client.java.CouchbaseCluster.create(CouchbaseCluster.java:157)
        at bca.peo.Cbase.<init>(Cbase.java:16)
        at bca.peo.MainVerticle.start(MainVerticle.java:20)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:552)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by ceejatec** [comment]
This GitHub repository is for the Couchbase Docker container, not for general Couchbase or SDK issues. I'd suggest starting at the Couchbase Forums for these kinds of questions: https://forums.couchbase.com/

At a guess, though, I think you want to remove "/pools" from your connection string.

**Comment by Tusshu** [comment]
Yes, that did it. Thanks a lot for your help!!!
